# Generated by Django 3.0.8 on 2020-09-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapp', '0004_forum_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='user',
            new_name='profile',
        ),
    ]
