# Generated by Django 3.0.8 on 2020-09-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapp', '0008_auto_20200908_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.AddField(
            model_name='forum',
            name='num_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
