# Generated by Django 3.0.8 on 2020-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapp', '0009_auto_20200909_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
