# Generated by Django 3.1.1 on 2020-09-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapp', '0012_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
